{"name": "test_wrong_login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: True\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00FE7413+2389011]\n\tOrdinal0 [0x00F79F61+1941345]\n\tOrdinal0 [0x00E6C658+837208]\n\tOrdinal0 [0x00E991DD+1020381]\n\tOrdinal0 [0x00E9949B+1021083]\n\tOrdinal0 [0x00EC6032+1204274]\n\tOrdinal0 [0x00EB4194+1130900]\n\tOrdinal0 [0x00EC4302+1196802]\n\tOrdinal0 [0x00EB3F66+1130342]\n\tOrdinal0 [0x00E8E546+976198]\n\tOrdinal0 [0x00E8F456+980054]\n\tGetHandleVerifier [0x01199632+1727522]\n\tGetHandleVerifier [0x0124BA4D+2457661]\n\tGetHandleVerifier [0x0107EB81+569713]\n\tGetHandleVerifier [0x0107DD76+566118]\n\tOrdinal0 [0x00F80B2B+1968939]\n\tOrdinal0 [0x00F85988+1989000]\n\tOrdinal0 [0x00F85A75+1989237]\n\tOrdinal0 [0x00F8ECB1+2026673]\n\tBaseThreadInitThunk [0x771BFA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x77397A7E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77397A4E+238]", "trace": "self = <pages.LoginPage.Check_Login object at 0x000002A16BC616C0>, locator = ('class name', 'mb-3Q'), time = 1\n\n    def find_element(self, locator, time=1):\n        try:\n>           return WebDriverWait(self.driver, time).until(expected_conditions.presence_of_element_located(locator),f\"Can't find element by locator {locator}\")\n\npages\\BaseApp.py:15: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"074273ad9d0728eefecaaa7e94ed590e\")>, method = <function presence_of_element_located.<locals>._predicate at 0x000002A16BDF6200>\nmessage = \"Can't find element by locator ('class name', 'mb-3Q')\"\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except InvalidSelectorException as e:\n                raise e\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: Can't find element by locator ('class name', 'mb-3Q')\nE       Stacktrace:\nE       Backtrace:\nE       \tOrdinal0 [0x00FE7413+2389011]\nE       \tOrdinal0 [0x00F79F61+1941345]\nE       \tOrdinal0 [0x00E6C658+837208]\nE       \tOrdinal0 [0x00E991DD+1020381]\nE       \tOrdinal0 [0x00E9949B+1021083]\nE       \tOrdinal0 [0x00EC6032+1204274]\nE       \tOrdinal0 [0x00EB4194+1130900]\nE       \tOrdinal0 [0x00EC4302+1196802]\nE       \tOrdinal0 [0x00EB3F66+1130342]\nE       \tOrdinal0 [0x00E8E546+976198]\nE       \tOrdinal0 [0x00E8F456+980054]\nE       \tGetHandleVerifier [0x01199632+1727522]\nE       \tGetHandleVerifier [0x0124BA4D+2457661]\nE       \tGetHandleVerifier [0x0107EB81+569713]\nE       \tGetHandleVerifier [0x0107DD76+566118]\nE       \tOrdinal0 [0x00F80B2B+1968939]\nE       \tOrdinal0 [0x00F85988+1989000]\nE       \tOrdinal0 [0x00F85A75+1989237]\nE       \tOrdinal0 [0x00F8ECB1+2026673]\nE       \tBaseThreadInitThunk [0x771BFA29+25]\nE       \tRtlGetAppContainerNamedObjectPath [0x77397A7E+286]\nE       \tRtlGetAppContainerNamedObjectPath [0x77397A4E+238]\n\nvenv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:89: TimeoutException\n\nDuring handling of the above exception, another exception occurred:\n\nbrowser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"074273ad9d0728eefecaaa7e94ed590e\")>\n\n    def test_wrong_login(browser):\n        main_page = Action_Login(browser)\n        main_page.go_to_site()\n        main_page.enter_login_and_password(\"admin1\", 'zj#KqU1')\n        main_page = Check_Login(browser)\n>       message = main_page.check_wrong_login_message()\n\nTests\\test_autorization.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\LoginPage.py:26: in check_wrong_login_message\n    wrong_login_message = self.find_element(SearchLocators.wrong_login_message)\npages\\BaseApp.py:17: in find_element\n    return WebDriverWait(self.driver, time).until(expected_conditions.presence_of_element_located(locator),f\"Can't find element by locator {locator}\" and self.driver.get_screenshot_as_file(str(locator) + ' ' + 'NOT FOUND.png'))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"074273ad9d0728eefecaaa7e94ed590e\")>, method = <function presence_of_element_located.<locals>._predicate at 0x000002A16BDF60E0>, message = True\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except InvalidSelectorException as e:\n                raise e\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: True\nE       Stacktrace:\nE       Backtrace:\nE       \tOrdinal0 [0x00FE7413+2389011]\nE       \tOrdinal0 [0x00F79F61+1941345]\nE       \tOrdinal0 [0x00E6C658+837208]\nE       \tOrdinal0 [0x00E991DD+1020381]\nE       \tOrdinal0 [0x00E9949B+1021083]\nE       \tOrdinal0 [0x00EC6032+1204274]\nE       \tOrdinal0 [0x00EB4194+1130900]\nE       \tOrdinal0 [0x00EC4302+1196802]\nE       \tOrdinal0 [0x00EB3F66+1130342]\nE       \tOrdinal0 [0x00E8E546+976198]\nE       \tOrdinal0 [0x00E8F456+980054]\nE       \tGetHandleVerifier [0x01199632+1727522]\nE       \tGetHandleVerifier [0x0124BA4D+2457661]\nE       \tGetHandleVerifier [0x0107EB81+569713]\nE       \tGetHandleVerifier [0x0107DD76+566118]\nE       \tOrdinal0 [0x00F80B2B+1968939]\nE       \tOrdinal0 [0x00F85988+1989000]\nE       \tOrdinal0 [0x00F85A75+1989237]\nE       \tOrdinal0 [0x00F8ECB1+2026673]\nE       \tBaseThreadInitThunk [0x771BFA29+25]\nE       \tRtlGetAppContainerNamedObjectPath [0x77397A7E+286]\nE       \tRtlGetAppContainerNamedObjectPath [0x77397A4E+238]\n\nvenv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:89: TimeoutException"}, "start": 1652777866346, "stop": 1652777872151, "uuid": "63b927d2-fe62-4c9f-8942-24aa3415d1e9", "historyId": "723fb3431838f8498d112e9051bc509b", "testCaseId": "14560c4f734ab761fabde47b607f8dc8", "fullName": "Tests.test_autorization#test_wrong_login", "labels": [{"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_autorization"}, {"name": "host", "value": "DESKTOP-13RCMAF"}, {"name": "thread", "value": "23328-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_autorization"}]}